core: commands: fix command users crash with Django 2
After upgrading Dockerfile to buster-backports in commit f778bc6
(included in version 1.34) and upgrading Django to version 2 all
"squad-admin users" commands fail with:
  File squad/core/management/commands/users.py", line 42, in __init__
    super().__init__(cmd, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given

To fix that, check Django version to pass correct number of arguments
to __init__() from Django CommandParser.

Signed-off-by: Michal Wojcik <michal.wojcik@linaro.org>