Revert "Added translation using Weblate (Sinhala)"
This reverts commit c665bbad84d46ed850810bf42e105a744c899f52 and e938ca0cc5b55a66c7ad685ba8622062b9787b81.

Django currently does not suppot Sinhala (unfortunately), so I'm reverting the translation commits and turning them into a PR.

See error log:
FAIL: test_locales_supported_by_django (test.test_i18n.TestI18N)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chaws/linaro/src/linaro/squad/test/test_i18n.py", line 15, in test_locales_supported_by_django
    self.assertEqual(intersection, languages, 'language code not supported by Django. Must be one of %r' % sorted(django_languages))
AssertionError: Items in the second set but not the first:
'si' : language code not supported by Django. Must be one of ['af', 'ar', 'ast', 'az', 'be', 'bg', 'bn', 'br', 'bs', 'ca', 'cs', 'cy', 'da', 'de', 'dsb', 'el', 'en', 'en-au', 'en-gb', 'eo', 'es', 'es-ar', 'es-co', 'es-mx', 'es-ni', 'es-ve', 'et', 'eu', 'fa', 'fi', 'fr', 'fy', 'ga', 'gd', 'gl', 'he', 'hi', 'hr', 'hsb', 'hu', 'hy', 'ia', 'id', 'io', 'is', 'it', 'ja', 'ka', 'kab', 'kk', 'km', 'kn', 'ko', 'lb', 'lt', 'lv', 'mk', 'ml', 'mn', 'mr', 'my', 'nb', 'ne', 'nl', 'nn', 'os', 'pa', 'pl', 'pt', 'pt-br', 'ro', 'ru', 'sk', 'sl', 'sq', 'sr', 'sr-latn', 'sv', 'sw', 'ta', 'te', 'th', 'tr', 'tt', 'udm', 'uk', 'ur', 'vi', 'zh-hans', 'zh-hant']

Signed-off-by: Charles Oliveira <charles.oliveira@linaro.org>