requirements: pin importlib-metadata
This fixes a bug of using an old version of importlib-metadata
that was causing a crash:

    INSTALLED_EXTENSIONS = metadata.entry_points(group='markdown.extensions')
    TypeError: entry_points() got an unexpected keyword argument 'group'

Signed-off-by: Charles Oliveira <charles.oliveira@linaro.org>